# Generated by Django 4.2.1 on 2023-07-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='reting',
            new_name='rating',
        ),
    ]
